version: '3.5'

services:
    newContainer:
        build:
            args:
                CONTAINER_NAME: newContainer
                CONTAINER_VERSION: 1.0.0
                FROM_BASE: alpine:3.7
            cache_from:
                - alpine:3.7
#                - base_container:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: newContainer
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: newContainer
        image: newContainer:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
#        ports:
#            - 8003:80
# only use when building a 'service container'
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log
