version: '3.5'

services:
    newContainer:
        build:
            args:
                CONTAINER_VERSION: 1.0.0
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180217
            cache_from:
                - alpine:3.6
                - base_container:20180217
            context: .
            dockerfile: Dockerfile
        container_name: newContainer
        environment:
            CONTAINER_NAME: newContainer
        hostname: newContainer
        image: newContainer:20180217
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
#        ports:
#            - 8003:80
# only use when building a 'service container'
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log 
