#!/bin/bash

#set -o verbose
set -o nounset
set -o errexit

function createStructure()
{
    local tools=${1:?"must pass parameter 'tools' to 'function ${FUNCNAME[0]}()'"}

    local -a dirs=( '02.packages' '03.users_groups' '04.downloads' '05.applications' '06.customizations' '07.permissions' '08.cleanup' )
    for dir in ${dirs[@]}; do
        mkdir -p "${tools}/container/${dir}"
        touch "${tools}/container/${dir}/.Do Not Delete"
    done
}

function createSymlinks()
{
    local tools=${1:?"must pass parameter 'tools' to 'function ${FUNCNAME[0]}()'"}
    local dr=${2:?"must pass parameter 'dr' to 'function ${FUNCNAME[0]}()'"}
    
    local dir="$( basename "$dr" )"
    [ $dir = '01.bashlib' ] && return 0

    cd "${tools}/container/${dir}"
    while read -r fl ;do
        local file="$( basename "$fl" )"
        [ -h "$file" ] && rm "$file"
        [ -e "$file" ] && rm "$file"
        echo "Creating symlink to ../../container_lib/${dir}/${file}"
        ln -s "../../container_lib/${dir}/${file}" .
    done < <(find "$dr" -maxdepth 1 -type f ! -name '.*')
}

function scanLibFolders()
{
    local tools=${1:?"must pass parameter 'tools' to 'function ${FUNCNAME[0]}()'"}

    cd "${tools}/container"
    [ -h 01.bashlib ] && rm -rf 01.bashlib
    [ -d 01.bashlib ] && rm -rf 01.bashlib
    [ -h build.sh ] && rm build.sh
    [ -e build.sh ] && rm build.sh

    # scan lib folders and create symlinks for any files found
    while read -r dr ;do
        createSymlinks "$tools" "$dr"        
    done < <(find "${TOOLS}/container_lib" -maxdepth 1 -type d -name '*.*' ! -path '.' ! -path './.*')

    cd "${tools}/container"
    echo "Creating symlink to ../container_lib/01.bashlib"
    ln -s ../container_lib/01.bashlib .
    echo "Creating symlink to ../container_lib/build.sh"
    ln -s ../container_lib/build.sh .
}


declare TOOLS="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )" 

if [ ! -d container ]; then
    createStructure "$TOOLS"
    scanLibFolders "$TOOLS"

elif [ -d container ] && [ -d container_lib ]; then
    scanLibFolders "$TOOLS"
fi
