version: '3.3'

services:
    newContainer:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION}"
                CONTAINER_NAME: newContainer
                FROM_BASE: ${DOCKER_REGISTRY:-}${OS:-}alpine:3.8
#                FROM_BASE: ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}${OS:-}alpine:3.8
#                - ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: newContainer
        container_name: newContainer
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: newContainer
        image: ${DOCKER_REGISTRY:-}${OS:-}newContainer:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
#        ports:
#            - 8003:80
# only use when building a 'service container'
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log
